[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.1.0"

authors = ["Zivid"]

# Description
title = "Zivid 3D Cameras"
description="Extension providing virtual Zivid 3D Cameras"
readme  = "docs/README.md"
repository = "https://github.com/zivid/zivid-isaac-sim"
category = "simulation"
keywords = ["kit", "robotics", "Sensor", "Zivid"]

icon = "assets/ZividStudio.png"

[python.pipapi]
requirements = [
    "numpy",
    "prettytable==3.3.0",
    "toml",
    "gymnasium==0.29.0",
    "cadquery",
]

modules = [
    "numpy"
]

use_online_index=true

[core]
reloadable = true

[[python.module]]
name = "isaacsim.zivid"

[dependencies]
"isaacsim.gui.menu" = {}
"omni.kit.widget.context_menu" = {}
